language: erlang
notifications:
  email: false
otp_release:
  - 22.0.5
  - 21.3.8
  - 21.1.4
  - 20.3.8
  - 19.3.6
  - 19.2
  - 18.3
  - 17.5
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R15B03
script: rebar compile && rebar eunit
