dist: trusty
language: erlang
notifications:
  email: false
otp_release:
  - 22.1.8
  - 22.0.7
  - 21.3.8
  - 21.1.4
  - 20.3.8
  - 19.3.6
  - 19.2
  - 18.3
  - 17.5
  - R16B03-1
script: rebar compile && rebar xref && rebar eunit
