name: Erlang rebar CI

on:
  push:
    branches:
    - master
    - 4.x
  pull_request:
    branches:
    - master
    - 4.x

jobs:
  erlang-23_2:
    runs-on: ubuntu-latest
    container:
      image: erlang:23.2.4
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-23_1:
    runs-on: ubuntu-latest
    container:
      image: erlang:23.1.5
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-23_0:
    runs-on: ubuntu-latest
    container:
      image: erlang:23.0.4
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-22_3:
    runs-on: ubuntu-latest
    container:
      image: erlang:22.3.4.15
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-22_2:
    runs-on: ubuntu-latest
    container:
      image: erlang:22.2.8
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-22_1:
    runs-on: ubuntu-latest
    container:
      image: erlang:22.1.8
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-22_0:
    runs-on: ubuntu-latest
    container:
      image: erlang:22.0.7
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-21_3:
    runs-on: ubuntu-latest
    container:
      image: erlang:21.3.8.20
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-21_2:
    runs-on: ubuntu-latest
    container:
      image: erlang:21.2.7
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-21_1:
    runs-on: ubuntu-latest
    container:
      image: erlang:21.1.4
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-21_0:
    runs-on: ubuntu-latest
    container:
      image: erlang:21.0.9
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-20_3:
    runs-on: ubuntu-latest
    container:
      image: erlang:20.3.8.26
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-20_2:
    runs-on: ubuntu-latest
    container:
      image: erlang:20.2.4
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-20_1:
    runs-on: ubuntu-latest
    container:
      image: erlang:20.1.7
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-20_0:
    runs-on: ubuntu-latest
    container:
      image: erlang:20.0.5
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-19_3:
    runs-on: ubuntu-latest
    container:
      image: erlang:19.3.6.13
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-19_2:
    runs-on: ubuntu-latest
    container:
      image: erlang:19.2.3
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-19_1:
    runs-on: ubuntu-latest
    container:
      image: erlang:19.1.6
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-19_0:
    runs-on: ubuntu-latest
    container:
      image: erlang:19.0.7
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit

  erlang-18_3:
    runs-on: ubuntu-latest
    container:
      image: erlang:18.3.4.11
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar compile
    - name: Run tests
      run: rebar xref && rebar eunit
