name: Erlang rebar CI

on:
  push:
    branches:
    - master
    - 4.x
    - 5.x
    - 6.x
  pull_request:
    branches:
    - master
    - 4.x
    - 5.x
    - 6.x

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [27.0, 26.2, 26.1, 26.0, 25.3, 25.2, 25.1, 25.0, 24.3, 24.2, 24.1, 24.0, 23.3, 23.2, 23.1, 23.0, 22.3, 22.2, 22.1, 22.0, 21.3, 21.2, 21.1, 21.0, 20.3, 20.2, 20.1, 20.0, 19.3]
        rebar: [rebar, rebar3]
    container:
      image: erlang:${{ matrix.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: ${{ matrix.rebar }} compile
    - name: Tests
      run: ${{ matrix.rebar }} xref && ${{ matrix.rebar }} eunit
